# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{require-me}
  s.version = "0.7.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kristian Mandrup"]
  s.date = %q{2010-05-29}
  s.description = %q{Lets you easily define how to include hierarchies of ruby files, and also apply inclusion/exclusion filters for what to include}
  s.email = %q{kmandrup@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    "lib/folder/folder.rb",
     "lib/folder/magic.rb",
     "lib/folder/magic_list.rb",
     "lib/playground.rb",
     "lib/require-dsl.rb",
     "lib/require-me.rb",
     "lib/util/util.rb"
  ]
  s.homepage = %q{http://github.com/kristianmandrup/require-magic}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Facilitates requiring select ruby files in folders}
  s.test_files = [
    "spec/blip.rb",
     "spec/dsl/blap.rb",
     "spec/dsl/blup.rb",
     "spec/dsl/require-dsl_spec.rb",
     "spec/require_more_spec.rb",
     "spec/spec_helper.rb",
     "test/test_require_folder.rb",
     "test/test_require_folders.rb",
     "test/test_require_folders_adv.rb",
     "test/unit_test_require.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<load-me>, [">= 0.1.0"])
      s.add_development_dependency(%q<rspec>, [">= 2.0.0"])
    else
      s.add_dependency(%q<load-me>, [">= 0.1.0"])
      s.add_dependency(%q<rspec>, [">= 2.0.0"])
    end
  else
    s.add_dependency(%q<load-me>, [">= 0.1.0"])
    s.add_dependency(%q<rspec>, [">= 2.0.0"])
  end
end

